project:
  type: book
  output-dir: docs

book:
  title: "Grade 12 Mathematics"
  subtitle: "A beginner's guide"
  author: "Katleho Nyoni"
  cover-image: images/KATIEUM.png
  chapters:
    - index.qmd
    - intro.qmd
    - Probability.qmd
    - Functions.qmd
    - SequenceSeries.qmd
    - Finance.qmd
    - Calculus.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

